### ISSUE TITLE
Warning: Unable to infer variable name for metaReactive because no srcref is available

### ISSUE THREAD

**Issue by EmilieCarneiro** [rstudio/shinymeta#112]
Hi,
I am having problems with MSQRob2Gui. After normalization, get the following error: ndim is greater than number of rows of data.
In the code I get the following warning: Unable to infer variable name for metaReactive because no srcref is available. Please report an issue to https://github.com/rstudio/shinymeta/issues/new.
Beside these warning I am able to run the analysis until the end but when I try to save the report I get the following error in the app: 
![image](https://user-images.githubusercontent.com/107934660/198255049-fce0eb6f-cfea-4166-8a31-c849ab9cde10.png)
Please let me know what I can do to solve this problem.
Best regards
Emilie

**Comment by cpsievert** [comment]
> warning: Unable to infer variable name for metaReactive because no srcref is available.

This can happen for a number of reasons. What is means is that `metaReactive()` isn't able to infer the `variableName` in something like:

```r
variableName <- metaReactive({
  ...
})
```

You should be able to fix that by letting `metaReactive()` explicitly know what the variable name should be:

```r
variableName <- metaReactive({
  ...
}, varname = "variableName")
```
