### ISSUE TITLE
Surprising edge case with control flow

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinymeta#24]
(I don't think this is necessary a bug, just another rough edge.)

Within `metaExpr` and `metaReactive`, the `!!` in the code body are expanded away right before execution (metaMode=FALSE) or return of the code (metaMode=TRUE). This might be surprising in some cases, where the `!!` expressions are in conditional branches.

It's not possible to protect those `!!` from expansion (i.e. metaMode=TRUE), fine, that's not surprising; but it might be surprising that even when we're in execution mode (metaMode=FALSE) the `!!` expressions are all expanded out ahead of time, which can cause other reactives/metareactives to run.

In the example below, a user might be surprised to see `never_run` printed at the console; after all, the `else` branch was never entered.

```r
library(shiny)
library(shinymeta)

ui <- ""

server <- function(input, output, session) {
  
  mr <- metaObserve({
    if (TRUE) {
      !!always_run()
    } else {
      !!never_run()
    }
  })
  
  always_run <- metaReactive({
    message("always_run")
  })
  
  never_run <- metaReactive({
    message("never_run")
  })
}

shinyApp(ui, server)
```

It might be nice if we could just ignore/strip the `!!` when `metaMode=FALSE`, but that might have a bad effect on dplyr code, that uses `!!` for other reasons (a problem we already have actually, but this would make it worse).

**Comment by cpsievert** [comment]
No longer a problem now after #59
