### ISSUE TITLE
Name inference fails without warning if { doesn't appear first

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shinymeta#61]
I'd expect name inference to work in this case, but maybe we can't get at the `srcref`?

```r
mr <- metaReactive(localize = TRUE, {
  1+1
})
expandChain(mr())
```

```r
var_1 <- local(1 + 1)
var_1
```

**Comment by jcheng5** [comment]
Yeah, that makes sense--the code that detects the varname is heuristics driven and fairly brittle. I thought we were warning though?

**Comment by cpsievert** [comment]
Oh, actually, the srcref is availble in this case, it's this regex that's failing https://github.com/rstudio/shinymeta/blob/0fd6b170b5d97fe52827d5906d195ef77cdc10e1/R/utils.R#L75

**Comment by cpsievert** [comment]
@jcheng5 maybe the fix is to simply remove the trailing `$` in that regex?
