### ISSUE TITLE
Publish to CRAN so that we could use shinymeta in our packages

### ISSUE THREAD

**Issue by daattali** [rstudio/shinymeta#79]
I understand that shinymeta is likely considered in beta and may not be not very active development at the moment, but I still think it'd be useful to publish the current version to CRAN.

shinymeta in its current form does allow us to do things that that would otherwise be very difficult, and even with its current limitations it's still extremely helpful. But unfortunately using shinymeta means that we cannot submit our package to CRAN since shinymeta isn't on CRAN.

**Comment by lz100** [comment]
@cpsievert @jcheng5 We are very thankful for your development of shinymeta. Could you publish it to CRAN so we can include shinymeta in our packages?

**Comment by daattali** [comment]
It would be useful to at least get some information regarding wherher (a) this is actively being worked on, (b) it's been shelved for now but it's ok putting the current version on CRAN, (c) it's shelved and RStudio doesn't feel comfortable putting a non polished product on CRAN

**Comment by jcheng5** [comment]
Yeah, sorry folks, we're pretty resource constrained right at this moment. @cpsievert let's discuss

**Comment by jcheng5** [comment]
Thanks for the nudge, people. I have a side thread working through the v1.0 issues, once those are done (especially #73) we will submit to CRAN.

**Comment by jcheng5** [comment]
I'm sorry this is taking so long, my side thread was preempted. I haven't forgotten about this though.

**Comment by daattali** [comment]
I know at least a 3 of us have been wondering last week, but didn't want to bug you, so thanks for letting us know :)

**Comment by nanxstats** [comment]
Amazing work. Any plans of a CRAN release in the new year?

**Comment by jcheng5** [comment]
Yes, I'm *so* sorry. I have a plan.

**Comment by cpsievert** [comment]
Now on CRAN, sorry for the wait!
