### ISSUE TITLE
env and quoted are deprecated

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinymeta#91]
Error messages with shiny 1.6.0 `devmode()`:

> The `env` and `quoted` arguments are deprecated as of shiny 1.6.0. Please use quosures from `rlang` instead.
> See <https://github.com/rstudio/shiny/issues/3108> for more information.

If we change shinymeta to use quosures, then we can't forget to bump the shiny dependency to >= 1.6.0.

**Comment by jcheng5** [comment]
@cpsievert and I tried fixing this today and couldn't get it to work. The example in https://github.com/rstudio/shiny/issues/3108 shows the same error we were getting: `Quosures can only be unquoted within a quasiquotation context.`

**Comment by cpsievert** [comment]
Winston is going to update that outdated example, but in case he doesn't get to it by the next time we meet:

```r
e <- new.env()
e$a <- 2
reactive(quote(a), quoted = TRUE, env = e)
```

Should become something like

```r
inject(reactive(!!new_quosure(a, e)))
```
